/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as MyComponentsRouteImport } from './routes/my-components'
import { Route as AddComponentRouteImport } from './routes/add-component'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ComponentsIndexRouteImport } from './routes/components/index'
import { Route as EditComponentIdRouteImport } from './routes/edit-component.$id'

const MyComponentsRoute = MyComponentsRouteImport.update({
  id: '/my-components',
  path: '/my-components',
  getParentRoute: () => rootRouteImport,
} as any)
const AddComponentRoute = AddComponentRouteImport.update({
  id: '/add-component',
  path: '/add-component',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsIndexRoute = ComponentsIndexRouteImport.update({
  id: '/components/',
  path: '/components/',
  getParentRoute: () => rootRouteImport,
} as any)
const EditComponentIdRoute = EditComponentIdRouteImport.update({
  id: '/edit-component/$id',
  path: '/edit-component/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/add-component': typeof AddComponentRoute
  '/my-components': typeof MyComponentsRoute
  '/edit-component/$id': typeof EditComponentIdRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/add-component': typeof AddComponentRoute
  '/my-components': typeof MyComponentsRoute
  '/edit-component/$id': typeof EditComponentIdRoute
  '/components': typeof ComponentsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/add-component': typeof AddComponentRoute
  '/my-components': typeof MyComponentsRoute
  '/edit-component/$id': typeof EditComponentIdRoute
  '/components/': typeof ComponentsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/add-component'
    | '/my-components'
    | '/edit-component/$id'
    | '/components/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/add-component'
    | '/my-components'
    | '/edit-component/$id'
    | '/components'
  id:
    | '__root__'
    | '/'
    | '/add-component'
    | '/my-components'
    | '/edit-component/$id'
    | '/components/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AddComponentRoute: typeof AddComponentRoute
  MyComponentsRoute: typeof MyComponentsRoute
  EditComponentIdRoute: typeof EditComponentIdRoute
  ComponentsIndexRoute: typeof ComponentsIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/my-components': {
      id: '/my-components'
      path: '/my-components'
      fullPath: '/my-components'
      preLoaderRoute: typeof MyComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/add-component': {
      id: '/add-component'
      path: '/add-component'
      fullPath: '/add-component'
      preLoaderRoute: typeof AddComponentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components/': {
      id: '/components/'
      path: '/components'
      fullPath: '/components/'
      preLoaderRoute: typeof ComponentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/edit-component/$id': {
      id: '/edit-component/$id'
      path: '/edit-component/$id'
      fullPath: '/edit-component/$id'
      preLoaderRoute: typeof EditComponentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AddComponentRoute: AddComponentRoute,
  MyComponentsRoute: MyComponentsRoute,
  EditComponentIdRoute: EditComponentIdRoute,
  ComponentsIndexRoute: ComponentsIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
